export const LOAD_PEOPLE_DEATAILS = 'LOAD_PEOPLE_DEATAILS'
export const LOAD_PEOPLE_DEATAILS_SUCCESS = 'LOAD_PEOPLE_DEATAILS_SUCCESS'
export const LOAD_PEOPLE_DEATAILS_FAILURE = 'LOAD_PEOPLE_DEATAILS_FAILURE'